/** Curated, refresh-ready registry of official Premier Bank sources. */
export type OfficialPremierSource = {
  id: string;
  source: "Premier Bank" | "Official Premier Bank Facebook";
  title: string;
  url: string;
  category: "accounts" | "cards" | "services" | "diaspora" | "support" | "announcements" | "community" | "awards" | "locations" | "identity";
  updatedAt: string;
  publishedAt?: string;
  city?: string;
  country?: string;
  status?: "current" | "historical" | "promotional" | "source-mentioned";
  content: string;
};

export const OFFICIAL_PREMIER_SOURCES: readonly OfficialPremierSource[] = [
  { id: "official-home", source: "Premier Bank", title: "Premier Bank – Banking Made Easy", url: "https://www.premierbank.so/", category: "support", updatedAt: "2026-08-29", content: "Official services include ATM, Premier Mastercard, Payroll, POS and SWIFT. Official account categories include Personal Current, Salary, Diaspora, Corporate Current, Business Current, Umma, Personal Saving, Hajj/Umrah and Student Savings." },
  { id: "official-mastercard", source: "Premier Bank", title: "Premier Mastercard", url: "https://www.premierbank.so/?thsn-service=mastercard", category: "cards", updatedAt: "2026-08-30", content: "Premier Mastercard supports internet and POS payments plus ATM cash withdrawals wherever the Mastercard logo is displayed. It is available for USD 2. User-provided official service information states that online and POS payments are fee-free. Card information includes Platinum, Corporate and World Elite; the official page also references Classic Mastercard." },
  { id: "official-atm", source: "Premier Bank", title: "ATM", url: "https://www.premierbank.so/?thsn-service=atm", category: "services", updatedAt: "2026-08-29", content: "Premier Bank ATM services include cash withdrawal, balance inquiry and mini-statements. ATM card access is described as 24 hours a day, 7 days a week; use the Branch Locator for a specific location." },
  { id: "official-diaspora", source: "Premier Bank", title: "Diaspora Banking Account", url: "https://www.premierbank.so/?thsn-service=diaspora-banking-account", category: "diaspora", updatedAt: "2026-08-29", content: "Diaspora Banking supports customers living abroad with accounts, saving, family support and investment planning. The official page names USA, UK and Kenya as current countries and lists Diaspora Current, Savings, Student, Junior Savings, Foreign Currency Savings, Wallet and Money Transfer, and ATM Mastercard and Visa solutions." },
  { id: "official-pos", source: "Premier Bank", title: "Premier POS", url: "https://www.premierbank.so/?thsn-service=pos", category: "services", updatedAt: "2026-08-29", content: "Premier POS accepts Premier Mastercard, Premier Consumer Card and other bank Visa, Mastercard and Discover cards. The official page says Premier POS is free inside Somalia." },
  { id: "official-products", source: "Premier Bank", title: "Products & Services Offering", url: "https://www.premierbank.so/products-services-offering/", category: "services", updatedAt: "2026-08-29", content: "Premier Bank offers mobile and internet banking for checking accounts, transacting, making payments and sending money. Delivery channels include branches, ATMs, internet banking and card services." },
  { id: "facebook-mastercard-campaign", source: "Official Premier Bank Facebook", title: "Premier Mastercard campaign", url: "https://www.facebook.com/premierbankso/", category: "cards", updatedAt: "2026-08-29", content: "Premier Mastercard may be used for purchases outside the country and for online shopping. The campaign requires spending at least USD 60; every additional USD 30 increases the chance of winning rewards. No campaign date, end date, or further terms are available in the supplied official content." },
  { id: "facebook-virtual-card", source: "Official Premier Bank Facebook", title: "Premier Virtual Card", url: "https://www.facebook.com/premierbankso/", category: "cards", updatedAt: "2026-08-30", content: "Premier Virtual Card is a digital card requested through Premier Wallet without visiting a branch. It can be used for online payments, including supported digital subscriptions such as ChatGPT, as well as other supported online services. It can be managed in Premier Wallet. User-provided official service information states that supported online payments are fee-free." },
  { id: "facebook-premier-tap", source: "Official Premier Bank Facebook", title: "Premier Tap", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", content: "Premier Tap is a modern contactless-payment solution. It supports tap payments on supported devices, including a ring and other Premier Tap devices, and is described as fast, convenient, secure and modern." },
  { id: "facebook-wallet-send", source: "Official Premier Bank Facebook", title: "Premier Wallet – Wallet Send", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", content: "Wallet Send supports international transfers to more than 110 countries. Funds may be sent to bank accounts, mobile wallets or cash pickup. Egypt is explicitly shown as selectable: open Premier Wallet, choose Wallet Send, choose Send Remittance, select Egypt, or use Show more countries. The supplied content does not confirm every individual country, including China." },
  { id: "facebook-sips", source: "Official Premier Bank Facebook", title: "SIPS domestic transfers", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", content: "Premier Bank customers can send and receive money with banks across Somalia through the SIPS instant money-transfer system. Account holders can manage their funds through Premier Wallet from anywhere and at any time." },
  { id: "facebook-simad", source: "Official Premier Bank Facebook", title: "SIMAD University partnership", url: "https://www.facebook.com/premierbankso/", category: "announcements", updatedAt: "2026-08-29", content: "SIMAD University students can pay supported university fees using Premier Wallet on their phones without going to payment centers. The partnership discussed financial services, education, innovation, economic development, productive and agricultural projects, MPGS-related cross-country payment management, LEAP Microfinance support for startups and SMEs, and Student Financing (Qardul Xasan)." },
  { id: "facebook-visa-payments-forum-2026", source: "Official Premier Bank Facebook", title: "Visa Payments Forum 2026", url: "https://www.facebook.com/premierbankso/", category: "announcements", updatedAt: "2026-08-29", publishedAt: "2026-07-02", content: "Premier Bank participated in Visa Payments Forum 2026 in Paris, France, from June 30 to July 2, 2026. Representatives included Dr. Mohamed Ghedi Jumale and Mr. Mahad Ahmed Mohamed. Topics included digital payments, AI, risk management, future financial services and international payment-system developments." },
  { id: "facebook-hajj-umrah", source: "Official Premier Bank Facebook", title: "Hajj and Umrah payment services", url: "https://www.facebook.com/premierbankso/", category: "cards", updatedAt: "2026-08-29", content: "Official content promotes Premier Mastercard and Premier Tap for Hajj and Umrah-related payments in Saudi Arabia, mentions collaboration with Haleel Hajj & Umrah Services and some gradual-payment Umrah packages. A stated promotion waived POS fees for Riyal payments using Premier Mastercard or Premier Tap; do not extend this temporary promotion beyond the supplied information." },
  { id: "facebook-security", source: "Official Premier Bank Facebook", title: "Fraud-awareness guidance", url: "https://www.facebook.com/premierbankso/", category: "support", updatedAt: "2026-08-29", content: "Premier Bank never requests a PIN, OTP, password or CVV through calls or messages. Customers should use official verified accounts, avoid suspicious links and fake accounts/messages, and protect banking information." },
  { id: "facebook-atm-jabane-hargeisa", source: "Official Premier Bank Facebook", title: "Jabane Supermarket ATMs, Hargeisa", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", content: "The supplied official announcement places Premier Bank ATMs at two Jabane Supermarket locations in Hargeisa. Mentioned services are cash withdrawal, PIN change, balance inquiry and other ATM services. The announced Ramadan hours were 08:00 AM–04:00 PM and must not be presented as current year-round hours. Customer service is described as 24/7." },
  { id: "facebook-wallet-registration-bills", source: "Official Premier Bank Facebook", title: "Premier Wallet registration and bill payments", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", content: "Registration flow: download Premier Wallet, select Sign Up, enter mobile number, full name and an identification type such as National ID or Passport, verify the mobile number by OTP, create a private PIN and complete registration. Never request an OTP or PIN. Bill payments include electricity bills: choose Bill Payments, select the bill, enter the required bill/meter/account details, confirm the amount and complete the payment. The content does not name an electricity provider or bill identifier." },
  { id: "facebook-payment-gateway", source: "Official Premier Bank Facebook", title: "Premier Payment Gateway", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", content: "Premier Payment Gateway is a digital payment solution for Somali businesses and merchants, in partnership with Mastercard and powered by Mastercard Payment Gateway Services (MPGS). It enables supported international card payments, supports Mastercard and other branded cards as described, online purchases, foreign-currency payments as described, and e-commerce growth. It is a business/merchant solution, not Premier Wallet or a personal Mastercard." },
  { id: "facebook-premier-tap-wearables", source: "Official Premier Bank Facebook", title: "Premier Tap wearable devices", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", content: "Premier Tap content describes NFC contactless payments through rings, wearable devices, wristbands, bracelets, key fobs, stickers, smartwatches/NFC-enabled watches, glasses/eyewear, and phone-based Tap to Pay. Availability, country-specific details and campaign terms must not be generalized beyond the supplied content." },
  { id: "facebook-wallet-core-services", source: "Official Premier Bank Facebook", title: "Premier Wallet core services", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", content: "Premier Wallet supports wallet top-up, money transfer, bill payments, deposit and withdrawal, mobile banking, balance checking, transaction history, exchange/currency conversion, international transfers, domestic transfers and financial management. Wallet-to-wallet transfers may use a QR code or contact information; transfers may be made to a bank account or an unregistered Wallet recipient. Never ask a customer for a PIN." },
  { id: "facebook-atm-cash-deposit-2024", source: "Official Premier Bank Facebook", title: "Premier Bank ATM Cash Deposit", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", publishedAt: "2024-08-22", content: "Premier Bank introduced ATM Cash Deposit on 22.08.2024. Supported ATMs allow customers to deposit cash into their account, described as real-time, secure and available 24/7. The supplied flow is: insert ATM/debit card, choose Cash Deposit, insert cash, confirm amount, complete transaction. Deposit limits, accepted note denominations, fees and supported locations are not supplied." },
  { id: "facebook-wallet-bills-and-exchange", source: "Official Premier Bank Facebook", title: "Premier Wallet bills and exchange", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-29", content: "Supported Premier Wallet bill-payment examples include electricity, TV and school/university fees, plus other supported recurring services. Choose Bill Payments/Utility or Fee Payments, select a service, enter the relevant account, meter, student or customer number, confirm the amount and complete payment. Exchange flow: select Exchange, choose currencies, enter amount, review displayed rate, confirm; USD to Somaliland Shilling is an example only and does not confirm all currency pairs." },
  { id: "facebook-csr-sos-childrens-villages", source: "Official Premier Bank Facebook", title: "SOS Children's Villages Somalia support", url: "https://www.facebook.com/premierbankso/", category: "community", updatedAt: "2026-08-30", status: "source-mentioned", content: "Premier Bank source-provided community/CSR information mentions support for SOS Children's Villages Somalia, including children's living expenses, healthcare and education." },
  { id: "facebook-somali-tech-awards-2025", source: "Official Premier Bank Facebook", title: "Somali Tech Awards and 2025 recognitions", url: "https://www.facebook.com/premierbankso/", category: "awards", updatedAt: "2026-08-30", status: "historical", content: "Source-provided award information includes Somali Tech Awards, Digital Banking Award, Digital Wallet Advancement Award, Best Mobile Money App of the Year 2025, First Wearable Commercial Launch in East Africa, and Outstanding African Banking Brand Excellence Award 2025. These are historical recognitions and must not be presented as current offers." },
  { id: "facebook-atm-safari-resort-borama", source: "Official Premier Bank Facebook", title: "Premier Bank ATM – Safari Resort Hotel", url: "https://www.facebook.com/premierbankso/", category: "locations", city: "Borama", country: "Somalia", updatedAt: "2026-08-30", status: "source-mentioned", content: "Source-provided ATM location: Safari Resort Hotel, Borama. Services may include cash withdrawal, PIN change, balance check, mini statement and Cash Deposit where supported; no address, hours or coordinates are supplied." },
  { id: "facebook-atm-bosaso-international-airport", source: "Official Premier Bank Facebook", title: "Premier Bank ATM – Bosaso International Airport", url: "https://www.facebook.com/premierbankso/", category: "locations", city: "Bosaso", country: "Somalia", updatedAt: "2026-08-30", status: "source-mentioned", content: "Source-provided ATM location: Bosaso International Airport, Bosaso. No address, hours or coordinates are supplied." },
  { id: "facebook-atm-al-jazeera-gaalkacyo", source: "Official Premier Bank Facebook", title: "Premier Bank ATM – Al Jazeera Hotel", url: "https://www.facebook.com/premierbankso/", category: "locations", city: "Gaalkacyo", country: "Somalia", updatedAt: "2026-08-30", status: "source-mentioned", content: "Source-provided ATM location: Al Jazeera Hotel, Gaalkacyo. No address, hours or coordinates are supplied." },
  { id: "facebook-atm-jabir-plaza-bosaso", source: "Official Premier Bank Facebook", title: "Premier Bank ATM – Jabir Plaza Hotel", url: "https://www.facebook.com/premierbankso/", category: "locations", city: "Bosaso", country: "Somalia", updatedAt: "2026-08-30", status: "source-mentioned", content: "Source-provided ATM location: Jabir Plaza Hotel, Bosaso. No address, hours or coordinates are supplied." },
  { id: "facebook-pos-merchant-examples", source: "Official Premier Bank Facebook", title: "Premier POS merchant examples", url: "https://www.facebook.com/premierbankso/", category: "locations", updatedAt: "2026-08-30", status: "source-mentioned", content: "Source-mentioned Premier POS merchant examples are Hyderabad Biryani, Al Jazeera Hotel in Gaalkacyo, and Jabir Plaza Hotel in Bosaso. These examples are not a complete merchant directory and do not confirm all businesses in those cities." },
  { id: "facebook-nira-ekyc-discussion", source: "Official Premier Bank Facebook", title: "NIRA, eKYC and financial inclusion discussion", url: "https://www.facebook.com/premierbankso/", category: "identity", updatedAt: "2026-08-30", status: "source-mentioned", content: "Source-provided information describes discussion of connecting NIRA/digital identity and eKYC with financial services and Premier Wallet to support financial inclusion. Technical integration details and current availability are not supplied." },
  { id: "official-premier-pos-merchant-locations", source: "Premier Bank", title: "Premier POS merchant locations", url: "https://www.premierbank.so/?thsn-service=pos", category: "locations", city: "Galkacyo and Bosaso", country: "Somalia", updatedAt: "2026-08-30", status: "source-mentioned", content: "User-provided official service information names Shaafici Pharmacy & Supermarket in Galkacyo and Al Macruuf Shopping Center in Bosaso, Puntland as locations where customers can make supported payments through Premier Bank POS." },
  { id: "official-premier-world-elite", source: "Premier Bank", title: "Premier World Elite Mastercard", url: "https://www.premierbank.so/?thsn-service=mastercard", category: "cards", updatedAt: "2026-08-30", status: "source-mentioned", content: "Premier World Elite Mastercard is intended for customers seeking premium international-travel benefits. User-provided service information mentions VIP services and access to supported international airport lounges and coffee shops. Price, eligibility, and the exact participating locations are not supplied." },
  { id: "official-premier-wallet-manager", source: "Premier Bank", title: "Premier Wallet Manager", url: "https://www.premierbank.so/", category: "services", updatedAt: "2026-08-30", status: "source-mentioned", content: "Premier Wallet Manager helps businesses manage and pay employee salaries in a modern, convenient way. Enza Home is mentioned as an example business user." },
  { id: "official-premier-atm-serene-sarovar", source: "Premier Bank", title: "Premier Bank ATM - Serene Sarovar Hotel", url: "https://www.premierbank.so/?thsn-service=atm", category: "locations", city: "Hargeisa", country: "Somalia", updatedAt: "2026-08-30", status: "source-mentioned", content: "User-provided service information identifies a Premier Bank ATM at SERENE SAROVAR Hotel, Hargeisa. Mentioned services include cash withdrawals, PIN changes, balance checks, and other available ATM services." },
  { id: "official-premier-best-service-award-2025", source: "Premier Bank", title: "Best Service Award 2025", url: "https://www.premierbank.so/", category: "awards", publishedAt: "2025-12-31", updatedAt: "2026-08-30", status: "historical", content: "Premier Bank received the Best Service Award 2025 from the Somali National Quality Assurance body (SOBS), according to user-provided official information." },
  { id: "official-premier-leap-program", source: "Premier Bank", title: "LEAP Program", url: "https://www.premierbank.so/", category: "community", updatedAt: "2026-08-30", status: "historical", content: "LEAP is a collaboration of Premier Bank, SIMAD iLab and Direct Aid. Its first cohort supported 25 innovative businesses with a total USD 300,000 in Qardu Xasan financing after 100 applicants participated. The program supports Somali youth, innovation, productivity and business growth." },
  { id: "official-premier-cup-2025-wallet-send", source: "Premier Bank", title: "Premier Cup 2025", url: "https://www.premierbank.so/", category: "announcements", publishedAt: "2025-12-31", updatedAt: "2026-08-30", status: "historical", content: "The Wallet Send team won the Premier Cup 2025, according to user-provided official information." },
  { id: "facebook-sos-and-community-detail", source: "Official Premier Bank Facebook", title: "SOS Children's Villages Somalia support detail", url: "https://www.facebook.com/premierbankso/", category: "community", updatedAt: "2026-08-30", status: "source-mentioned", content: "User-provided official information states that Premier Bank sponsored part of the children at SOS Children's Villages Somalia and contributed to living expenses, healthcare and education. Dr. Mohamed Ghedi Jumale stated an intention to continue this support commitment." },
  { id: "facebook-somali-tech-awards-detail", source: "Official Premier Bank Facebook", title: "Somali Tech Awards detail", url: "https://www.facebook.com/premierbankso/", category: "awards", updatedAt: "2026-08-30", status: "historical", content: "User-provided official information states that Premier Bank received the Digital Banking Award after being the first bank in Somalia to implement an ATM cash-deposit machine, while Premier Wallet received the Digital Wallet Advancement Award." },
  { id: "facebook-wallet-send-egypt", source: "Official Premier Bank Facebook", title: "Wallet Send to Egypt", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-30", status: "source-mentioned", content: "Egypt is explicitly mentioned as a Wallet Send remittance destination. The supplied flow is Premier Wallet, Wallet Send, Send Remittance, then Egypt; use Show more countries if Egypt is not immediately shown. The exact fee is not supplied and must not be guessed." },
  { id: "facebook-wallet-extended-services", source: "Official Premier Bank Facebook", title: "Premier Wallet extended services", url: "https://www.facebook.com/premierbankso/", category: "services", updatedAt: "2026-08-30", status: "source-mentioned", content: "User-provided information says Premier Wallet supports eligible water, education, TV/Cable and healthcare bill payments, wallet-to-wallet and wallet-to-bank-account transfers, remittances, QR or Merchant ID payments, airtime top-up, supported in-app currency exchange and transaction history. It also states money may be sent to a recipient without a Wallet; limits, fees and provider availability are not supplied." },
  { id: "facebook-diaspora-account-detail", source: "Official Premier Bank Facebook", title: "Diaspora Banking Account detail", url: "https://www.facebook.com/premierbankso/", category: "diaspora", updatedAt: "2026-08-30", status: "source-mentioned", content: "User-provided information says a Diaspora Account can be opened from abroad through a supported approved agency without travelling to Somalia. It mentions a dedicated Diaspora team, saving, family support and future investment planning. Passport or National ID, an application form and other requested evidence are listed. The full supported-country list must be confirmed with Premier Bank. Information about relationship managers and property or land financing specifically refers to Premier Bank Kenya and must not be treated as a Premier Bank Somalia service without confirmation." },
  { id: "facebook-awards-2025-detail", source: "Official Premier Bank Facebook", title: "Premier Bank and Premier Wallet awards 2025", url: "https://www.facebook.com/premierbankso/", category: "awards", updatedAt: "2026-08-30", status: "historical", content: "User-provided historical information says Premier Bank Somalia Limited received the Outstanding African Banking Brand Excellence Award 2025 at the 15th African Business Leadership Awards during the ALM Africa Summit in London; Chairman Jibril Xasan Maxamed accepted it. It also says Premier Wallet received Best Mobile Money App of the Year 2025 from Somali Business Awards, accepted by Mohamed Ali Adam. Premier Bank also received First Wearable Commercial Launch in East Africa at Mastercard Edge 2025." },
  { id: "official-haleel-service", source: "Premier Bank", title: "Haleel Hajj and Umrah Instalment Service", url: "https://www.premierbank.so/author/premierbank/", category: "services", updatedAt: "2026-08-30", status: "current", content: "Haleel is a Premier Bank and Hajj, Umrah Network Somalia (HUNSo) partnership that makes Hajj and Umrah more accessible through an interest-free instalment payment system. User-provided official service information states a minimum 30% initial package payment, with the remaining balance payable by an agreed instalment plan within one year. The Umrah service period is Muharram through Ramadan; package prices, monthly instalment amounts, and passport eligibility beyond Somali passports must be confirmed with Premier Bank or HUNSo." },
  { id: "official-senior-management", source: "Premier Bank", title: "Senior Management", url: "https://www.premierbank.so/?page_id=13828", category: "support", updatedAt: "2026-08-30", status: "current", content: "Official Senior Management page lists Mohamed Ghedi Jumale as Chief Executive Officer; Abdirashid Ali Adle as Head of Investment & Financing; Abdishakur Mohamed Afrah as Head of Corporate, SME and Retail; Mahad Ahmed Mohamed as Head of Operation; Abdinasir Hassan Ali as Head of IT; Mohamed Abdirahman Sheik as Head of Finance; Safia Abdi Abdullahi as Head of Risk & Compliance; Sayid Omar Ali Abubakar as Head of Internal Audit; Mohamed Ali Adam as Head of Digital Banking - Premier Wallet; and Isak Mohamed Ali as Head of Human Resources & Administration." },
  { id: "official-management-appointment-2024", source: "Premier Bank", title: "Managing Director appointment", url: "https://www.premierbank.so/author/premierbank/", category: "announcements", publishedAt: "2024-05-25", updatedAt: "2026-08-30", status: "historical", content: "Premier Bank's 2024 press release states that Dr. Mohamed Ghedi Jumale succeeded Osman Duale Ahmed. User-provided official information names Jibril Hassan as Chairman in the 2024 leadership appointment information." },
];

/** Official social endpoints may be ingested by a future server-side sync job. */
export const OFFICIAL_PREMIER_SOCIAL_SOURCES = [
  "https://www.facebook.com/premierbankso/",
  "https://www.instagram.com/premierbankso/",
  "https://twitter.com/premierbankSO",
  "https://www.linkedin.com/company/premier-bank-so",
  "https://www.youtube.com/channel/UCw3yoOilntIYZrqKR1uisKg",
] as const;

export const OFFICIAL_PREMIER_SOURCES_CONTEXT = OFFICIAL_PREMIER_SOURCES.map((source) => `[${source.title}] (${source.url}; updated ${source.updatedAt})\n${source.content}`).join("\n\n");
